name: mysqld-integration-test integration mariadb Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install mariadb server
        run: |
          sudo apt-get -y install mariadb-server
      - name: Build and install code
        run: |
          python -m build
          pip install dist/*.gz
          #      - name: Setup upterm session
          #        uses: lhotari/action-upterm@v1
      - name: Test with pytest
        run: |
          pytest -m integration_test
