name: testtest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install mariadb server
        run: |
          sudo apt-get -y install mariadb-server
      - name: Build and install code
        run: |
          python -m build
          pip install dist/*.gz
      - name: Write script
        run: |
          echo "#!/usr/bin/env python3" >> test.py
          echo "from mysqld_integration_test import Mysqld" >> test.py
          echo "mysqld = Mysqld(log_level='DEBUG')" >> test.py
          echo "instance = mysqld.run()" >> test.py
          chmod 755 test.py

      - name: Test
        run: |
          ./test.py
